// Terms of Service + Privacy Policy shown in-app (AuthGate legal modal).
// DRAFT — have an attorney review before this gates real paying users.
// Placeholder entity name below ("Frontline Coach") — swap in your registered
// business name once you have one.

export const LAST_UPDATED = "July 20, 2026";

export const TERMS_SECTIONS = [
  {
    heading: "1. Acceptance of Terms",
    body: [
      "By creating an account or using Frontline Coach (\"the Service\"), you agree to these Terms of Service. If you don't agree, don't use the Service.",
    ],
  },
  {
    heading: "2. What the Service Is",
    body: [
      "Frontline Coach is an AI-assisted coaching tool for managers and supervisors. It generates suggested language, practice scenarios, and documentation drafts based on information you provide.",
    ],
  },
  {
    heading: "3. Not Legal, HR, or Professional Advice",
    body: [
      "The Service provides general coaching guidance only. It is not legal advice, HR advice, or a substitute for consulting a qualified attorney, HR professional, or your employer's policies. Any employment action you take — including discipline, termination, or documentation — is your responsibility. Always follow your company's policies and applicable law.",
    ],
  },
  {
    heading: "4. Eligibility & Accounts",
    body: [
      "You must be at least 18 years old to use the Service. You're responsible for keeping your login credentials secure and for all activity under your account. Tell us right away if you suspect unauthorized use.",
    ],
  },
  {
    heading: "5. Acceptable Use",
    body: [
      "Don't use the Service to generate content intended to harass, discriminate against, or retaliate against an employee in violation of law. Don't attempt to reverse-engineer, scrape, or resell the Service without permission.",
    ],
  },
  {
    heading: "6. AI-Generated Content",
    body: [
      "Responses are generated by AI models and may occasionally be inaccurate, incomplete, or inappropriate for your specific situation. Review all suggested language before using it in a real conversation, coaching session, or written record.",
    ],
  },
  {
    heading: "7. Your Content & Session Data",
    body: [
      "You retain ownership of what you type into the Service. We log session inputs and outputs to operate the Service, protect against abuse, and (with your data) improve coaching quality over time. See the Privacy Policy below for details.",
    ],
  },
  {
    heading: "8. Subscription & Payment",
    body: [
      "If you're on a paid plan, fees are billed as disclosed at signup. Subscriptions renew automatically until canceled. No refunds for partial billing periods except where required by law.",
    ],
  },
  {
    heading: "9. Termination",
    body: [
      "We may suspend or terminate accounts that violate these Terms. You can stop using the Service and request account deletion at any time.",
    ],
  },
  {
    heading: "10. Disclaimer of Warranties",
    body: [
      "The Service is provided \"as is\" without warranties of any kind, express or implied, including fitness for a particular purpose or non-infringement.",
    ],
  },
  {
    heading: "11. Limitation of Liability",
    body: [
      "To the maximum extent permitted by law, Frontline Coach is not liable for indirect, incidental, or consequential damages arising from your use of the Service, including employment decisions made using its output.",
    ],
  },
  {
    heading: "12. Changes to These Terms",
    body: [
      "We may update these Terms from time to time. Continued use of the Service after a change means you accept the updated Terms.",
    ],
  },
  {
    heading: "13. Contact",
    body: ["Questions about these Terms? Reach out through the app's support contact."],
  },
];

export const PRIVACY_SECTIONS = [
  {
    heading: "1. Information We Collect",
    body: [
      "Account info: email address and authentication data (handled by our auth provider, Supabase).",
      "Usage data: the inputs you provide to each coaching tool and the outputs generated, timestamped, and linked to your account.",
    ],
  },
  {
    heading: "2. How We Use It",
    body: [
      "To operate and improve the Service, including generating coaching responses, maintaining session history so context carries across visits, and reviewing flagged content for abuse or quality issues.",
    ],
  },
  {
    heading: "3. AI Processing",
    body: [
      "Your inputs are sent to Anthropic's Claude API to generate responses. Anthropic processes this data under its own API terms; we do not control Anthropic's model training practices for API traffic beyond what its terms specify.",
    ],
  },
  {
    heading: "4. Where Data Lives",
    body: [
      "Account and session data is stored in Supabase (hosted Postgres). Access is restricted so each user can only read their own session history; broader access is limited to what's needed for abuse review and service operation.",
    ],
  },
  {
    heading: "5. Data Sharing",
    body: [
      "We don't sell your data. We share it only with the service providers needed to run Frontline Coach (Anthropic for AI processing, Supabase for storage/auth, Netlify for hosting) and if required by law.",
    ],
  },
  {
    heading: "6. Your Rights",
    body: [
      "You can request a copy of your data or ask us to delete your account and associated data at any time, subject to reasonable verification and any legal retention requirements.",
    ],
  },
  {
    heading: "7. Children's Privacy",
    body: ["The Service isn't directed at anyone under 18, and we don't knowingly collect data from minors."],
  },
  {
    heading: "8. Security",
    body: [
      "We use industry-standard practices (encrypted transport, access-controlled database policies) to protect your data, but no system is 100% secure.",
    ],
  },
  {
    heading: "9. Changes to This Policy",
    body: ["We'll update this page if our data practices change materially."],
  },
];
